/*
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.project.browserautomation.services.BadGrammarAccess;

@SuppressWarnings("all")
public class BadSyntacticSequencer extends AbstractSyntacticSequencer {

	protected BadGrammarAccess grammarAccess;
	protected AbstractElementAlias match_CheckboxAction_ALLKeyword_2_0_q;
	protected AbstractElementAlias match_ClickOn_VARKeyword_0_2_1_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (BadGrammarAccess) access;
		match_CheckboxAction_ALLKeyword_2_0_q = new TokenAlias(false, true, grammarAccess.getCheckboxActionAccess().getALLKeyword_2_0());
		match_ClickOn_VARKeyword_0_2_1_0_p = new TokenAlias(true, false, grammarAccess.getClickOnAccess().getVARKeyword_0_2_1_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_CheckboxAction_ALLKeyword_2_0_q.equals(syntax))
				emit_CheckboxAction_ALLKeyword_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ClickOn_VARKeyword_0_2_1_0_p.equals(syntax))
				emit_ClickOn_VARKeyword_0_2_1_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'ALL'?
	 *
	 * This ambiguous syntax occurs at:
	 *     bool=BoolString (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_CheckboxAction_ALLKeyword_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'VAR'+
	 *
	 * This ambiguous syntax occurs at:
	 *     type=ClickType (ambiguity) varname=STRING
	 
	 * </pre>
	 */
	protected void emit_ClickOn_VARKeyword_0_2_1_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
