/*
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.project.browserautomation.parser.antlr.internal.InternalBadParser;
import org.project.browserautomation.services.BadGrammarAccess;

public class BadParser extends AbstractAntlrParser {

	@Inject
	private BadGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBadParser createParser(XtextTokenStream stream) {
		return new InternalBadParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public BadGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BadGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
