/**
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation.bad;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.project.browserautomation.bad.BadPackage
 * @generated
 */
public interface BadFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BadFactory eINSTANCE = org.project.browserautomation.bad.impl.BadFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Program</em>'.
   * @generated
   */
  Program createProgram();

  /**
   * Returns a new object of class '<em>Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Instruction</em>'.
   * @generated
   */
  Instruction createInstruction();

  /**
   * Returns a new object of class '<em>Navigate To Url</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Navigate To Url</em>'.
   * @generated
   */
  NavigateToUrl createNavigateToUrl();

  /**
   * Returns a new object of class '<em>Check Exists</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Check Exists</em>'.
   * @generated
   */
  CheckExists createCheckExists();

  /**
   * Returns a new object of class '<em>Click On</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Click On</em>'.
   * @generated
   */
  ClickOn createClickOn();

  /**
   * Returns a new object of class '<em>Checkbox Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Checkbox Action</em>'.
   * @generated
   */
  CheckboxAction createCheckboxAction();

  /**
   * Returns a new object of class '<em>Fill Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fill Field</em>'.
   * @generated
   */
  FillField createFillField();

  /**
   * Returns a new object of class '<em>Store Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Store Element</em>'.
   * @generated
   */
  StoreElement createStoreElement();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  BadPackage getBadPackage();

} //BadFactory
