/**
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation.bad;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fill Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.project.browserautomation.bad.FillField#getId <em>Id</em>}</li>
 *   <li>{@link org.project.browserautomation.bad.FillField#getValue <em>Value</em>}</li>
 *   <li>{@link org.project.browserautomation.bad.FillField#getVarname <em>Varname</em>}</li>
 * </ul>
 *
 * @see org.project.browserautomation.bad.BadPackage#getFillField()
 * @model
 * @generated
 */
public interface FillField extends Instruction
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.project.browserautomation.bad.BadPackage#getFillField_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.project.browserautomation.bad.FillField#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see org.project.browserautomation.bad.BadPackage#getFillField_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link org.project.browserautomation.bad.FillField#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Varname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Varname</em>' attribute.
   * @see #setVarname(String)
   * @see org.project.browserautomation.bad.BadPackage#getFillField_Varname()
   * @model
   * @generated
   */
  String getVarname();

  /**
   * Sets the value of the '{@link org.project.browserautomation.bad.FillField#getVarname <em>Varname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Varname</em>' attribute.
   * @see #getVarname()
   * @generated
   */
  void setVarname(String value);

} // FillField
