/**
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation.bad;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.project.browserautomation.bad.BadFactory
 * @model kind="package"
 * @generated
 */
public interface BadPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "bad";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.project.org/browserautomation/Bad";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "bad";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BadPackage eINSTANCE = org.project.browserautomation.bad.impl.BadPackageImpl.init();

  /**
   * The meta object id for the '{@link org.project.browserautomation.bad.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.project.browserautomation.bad.impl.ProgramImpl
   * @see org.project.browserautomation.bad.impl.BadPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__INSTRUCTIONS = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.project.browserautomation.bad.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.project.browserautomation.bad.impl.InstructionImpl
   * @see org.project.browserautomation.bad.impl.BadPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 1;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.project.browserautomation.bad.impl.NavigateToUrlImpl <em>Navigate To Url</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.project.browserautomation.bad.impl.NavigateToUrlImpl
   * @see org.project.browserautomation.bad.impl.BadPackageImpl#getNavigateToUrl()
   * @generated
   */
  int NAVIGATE_TO_URL = 2;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAVIGATE_TO_URL__URL = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Navigate To Url</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAVIGATE_TO_URL_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.project.browserautomation.bad.impl.CheckExistsImpl <em>Check Exists</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.project.browserautomation.bad.impl.CheckExistsImpl
   * @see org.project.browserautomation.bad.impl.BadPackageImpl#getCheckExists()
   * @generated
   */
  int CHECK_EXISTS = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_EXISTS__TYPE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_EXISTS__ID = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Varname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_EXISTS__VARNAME = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Check Exists</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_EXISTS_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.project.browserautomation.bad.impl.ClickOnImpl <em>Click On</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.project.browserautomation.bad.impl.ClickOnImpl
   * @see org.project.browserautomation.bad.impl.BadPackageImpl#getClickOn()
   * @generated
   */
  int CLICK_ON = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_ON__TYPE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_ON__ID = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Varname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_ON__VARNAME = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Pos index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_ON__POS_INDEX = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Id combo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_ON__ID_COMBO = INSTRUCTION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>To select</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_ON__TO_SELECT = INSTRUCTION_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Click On</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_ON_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link org.project.browserautomation.bad.impl.CheckboxActionImpl <em>Checkbox Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.project.browserautomation.bad.impl.CheckboxActionImpl
   * @see org.project.browserautomation.bad.impl.BadPackageImpl#getCheckboxAction()
   * @generated
   */
  int CHECKBOX_ACTION = 5;

  /**
   * The feature id for the '<em><b>Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX_ACTION__BOOL = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Actions</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX_ACTION__ACTIONS = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Checkbox Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX_ACTION_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.project.browserautomation.bad.impl.FillFieldImpl <em>Fill Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.project.browserautomation.bad.impl.FillFieldImpl
   * @see org.project.browserautomation.bad.impl.BadPackageImpl#getFillField()
   * @generated
   */
  int FILL_FIELD = 6;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_FIELD__ID = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_FIELD__VALUE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Varname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_FIELD__VARNAME = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Fill Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_FIELD_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.project.browserautomation.bad.impl.StoreElementImpl <em>Store Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.project.browserautomation.bad.impl.StoreElementImpl
   * @see org.project.browserautomation.bad.impl.BadPackageImpl#getStoreElement()
   * @generated
   */
  int STORE_ELEMENT = 7;

  /**
   * The feature id for the '<em><b>Pos index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_ELEMENT__POS_INDEX = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Id from</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_ELEMENT__ID_FROM = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Prop name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_ELEMENT__PROP_NAME = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Varname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_ELEMENT__VARNAME = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Store Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_ELEMENT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.project.browserautomation.bad.ClickType <em>Click Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.project.browserautomation.bad.ClickType
   * @see org.project.browserautomation.bad.impl.BadPackageImpl#getClickType()
   * @generated
   */
  int CLICK_TYPE = 8;

  /**
   * The meta object id for the '{@link org.project.browserautomation.bad.ElemType <em>Elem Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.project.browserautomation.bad.ElemType
   * @see org.project.browserautomation.bad.impl.BadPackageImpl#getElemType()
   * @generated
   */
  int ELEM_TYPE = 9;

  /**
   * The meta object id for the '{@link org.project.browserautomation.bad.BoolString <em>Bool String</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.project.browserautomation.bad.BoolString
   * @see org.project.browserautomation.bad.impl.BadPackageImpl#getBoolString()
   * @generated
   */
  int BOOL_STRING = 10;


  /**
   * Returns the meta object for class '{@link org.project.browserautomation.bad.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.project.browserautomation.bad.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link org.project.browserautomation.bad.Program#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instructions</em>'.
   * @see org.project.browserautomation.bad.Program#getInstructions()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Instructions();

  /**
   * Returns the meta object for class '{@link org.project.browserautomation.bad.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see org.project.browserautomation.bad.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for class '{@link org.project.browserautomation.bad.NavigateToUrl <em>Navigate To Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Navigate To Url</em>'.
   * @see org.project.browserautomation.bad.NavigateToUrl
   * @generated
   */
  EClass getNavigateToUrl();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.NavigateToUrl#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.project.browserautomation.bad.NavigateToUrl#getUrl()
   * @see #getNavigateToUrl()
   * @generated
   */
  EAttribute getNavigateToUrl_Url();

  /**
   * Returns the meta object for class '{@link org.project.browserautomation.bad.CheckExists <em>Check Exists</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Check Exists</em>'.
   * @see org.project.browserautomation.bad.CheckExists
   * @generated
   */
  EClass getCheckExists();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.CheckExists#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.project.browserautomation.bad.CheckExists#getType()
   * @see #getCheckExists()
   * @generated
   */
  EAttribute getCheckExists_Type();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.CheckExists#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.project.browserautomation.bad.CheckExists#getId()
   * @see #getCheckExists()
   * @generated
   */
  EAttribute getCheckExists_Id();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.CheckExists#getVarname <em>Varname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Varname</em>'.
   * @see org.project.browserautomation.bad.CheckExists#getVarname()
   * @see #getCheckExists()
   * @generated
   */
  EAttribute getCheckExists_Varname();

  /**
   * Returns the meta object for class '{@link org.project.browserautomation.bad.ClickOn <em>Click On</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click On</em>'.
   * @see org.project.browserautomation.bad.ClickOn
   * @generated
   */
  EClass getClickOn();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.ClickOn#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.project.browserautomation.bad.ClickOn#getType()
   * @see #getClickOn()
   * @generated
   */
  EAttribute getClickOn_Type();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.ClickOn#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.project.browserautomation.bad.ClickOn#getId()
   * @see #getClickOn()
   * @generated
   */
  EAttribute getClickOn_Id();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.ClickOn#getVarname <em>Varname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Varname</em>'.
   * @see org.project.browserautomation.bad.ClickOn#getVarname()
   * @see #getClickOn()
   * @generated
   */
  EAttribute getClickOn_Varname();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.ClickOn#getPos_index <em>Pos index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pos index</em>'.
   * @see org.project.browserautomation.bad.ClickOn#getPos_index()
   * @see #getClickOn()
   * @generated
   */
  EAttribute getClickOn_Pos_index();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.ClickOn#getId_combo <em>Id combo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id combo</em>'.
   * @see org.project.browserautomation.bad.ClickOn#getId_combo()
   * @see #getClickOn()
   * @generated
   */
  EAttribute getClickOn_Id_combo();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.ClickOn#getTo_select <em>To select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>To select</em>'.
   * @see org.project.browserautomation.bad.ClickOn#getTo_select()
   * @see #getClickOn()
   * @generated
   */
  EAttribute getClickOn_To_select();

  /**
   * Returns the meta object for class '{@link org.project.browserautomation.bad.CheckboxAction <em>Checkbox Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Checkbox Action</em>'.
   * @see org.project.browserautomation.bad.CheckboxAction
   * @generated
   */
  EClass getCheckboxAction();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.CheckboxAction#getBool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool</em>'.
   * @see org.project.browserautomation.bad.CheckboxAction#getBool()
   * @see #getCheckboxAction()
   * @generated
   */
  EAttribute getCheckboxAction_Bool();

  /**
   * Returns the meta object for the attribute list '{@link org.project.browserautomation.bad.CheckboxAction#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Actions</em>'.
   * @see org.project.browserautomation.bad.CheckboxAction#getActions()
   * @see #getCheckboxAction()
   * @generated
   */
  EAttribute getCheckboxAction_Actions();

  /**
   * Returns the meta object for class '{@link org.project.browserautomation.bad.FillField <em>Fill Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fill Field</em>'.
   * @see org.project.browserautomation.bad.FillField
   * @generated
   */
  EClass getFillField();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.FillField#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.project.browserautomation.bad.FillField#getId()
   * @see #getFillField()
   * @generated
   */
  EAttribute getFillField_Id();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.FillField#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.project.browserautomation.bad.FillField#getValue()
   * @see #getFillField()
   * @generated
   */
  EAttribute getFillField_Value();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.FillField#getVarname <em>Varname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Varname</em>'.
   * @see org.project.browserautomation.bad.FillField#getVarname()
   * @see #getFillField()
   * @generated
   */
  EAttribute getFillField_Varname();

  /**
   * Returns the meta object for class '{@link org.project.browserautomation.bad.StoreElement <em>Store Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Store Element</em>'.
   * @see org.project.browserautomation.bad.StoreElement
   * @generated
   */
  EClass getStoreElement();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.StoreElement#getPos_index <em>Pos index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pos index</em>'.
   * @see org.project.browserautomation.bad.StoreElement#getPos_index()
   * @see #getStoreElement()
   * @generated
   */
  EAttribute getStoreElement_Pos_index();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.StoreElement#getId_from <em>Id from</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id from</em>'.
   * @see org.project.browserautomation.bad.StoreElement#getId_from()
   * @see #getStoreElement()
   * @generated
   */
  EAttribute getStoreElement_Id_from();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.StoreElement#getProp_name <em>Prop name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prop name</em>'.
   * @see org.project.browserautomation.bad.StoreElement#getProp_name()
   * @see #getStoreElement()
   * @generated
   */
  EAttribute getStoreElement_Prop_name();

  /**
   * Returns the meta object for the attribute '{@link org.project.browserautomation.bad.StoreElement#getVarname <em>Varname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Varname</em>'.
   * @see org.project.browserautomation.bad.StoreElement#getVarname()
   * @see #getStoreElement()
   * @generated
   */
  EAttribute getStoreElement_Varname();

  /**
   * Returns the meta object for enum '{@link org.project.browserautomation.bad.ClickType <em>Click Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Click Type</em>'.
   * @see org.project.browserautomation.bad.ClickType
   * @generated
   */
  EEnum getClickType();

  /**
   * Returns the meta object for enum '{@link org.project.browserautomation.bad.ElemType <em>Elem Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Elem Type</em>'.
   * @see org.project.browserautomation.bad.ElemType
   * @generated
   */
  EEnum getElemType();

  /**
   * Returns the meta object for enum '{@link org.project.browserautomation.bad.BoolString <em>Bool String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Bool String</em>'.
   * @see org.project.browserautomation.bad.BoolString
   * @generated
   */
  EEnum getBoolString();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BadFactory getBadFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.project.browserautomation.bad.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.project.browserautomation.bad.impl.ProgramImpl
     * @see org.project.browserautomation.bad.impl.BadPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__INSTRUCTIONS = eINSTANCE.getProgram_Instructions();

    /**
     * The meta object literal for the '{@link org.project.browserautomation.bad.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.project.browserautomation.bad.impl.InstructionImpl
     * @see org.project.browserautomation.bad.impl.BadPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '{@link org.project.browserautomation.bad.impl.NavigateToUrlImpl <em>Navigate To Url</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.project.browserautomation.bad.impl.NavigateToUrlImpl
     * @see org.project.browserautomation.bad.impl.BadPackageImpl#getNavigateToUrl()
     * @generated
     */
    EClass NAVIGATE_TO_URL = eINSTANCE.getNavigateToUrl();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAVIGATE_TO_URL__URL = eINSTANCE.getNavigateToUrl_Url();

    /**
     * The meta object literal for the '{@link org.project.browserautomation.bad.impl.CheckExistsImpl <em>Check Exists</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.project.browserautomation.bad.impl.CheckExistsImpl
     * @see org.project.browserautomation.bad.impl.BadPackageImpl#getCheckExists()
     * @generated
     */
    EClass CHECK_EXISTS = eINSTANCE.getCheckExists();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECK_EXISTS__TYPE = eINSTANCE.getCheckExists_Type();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECK_EXISTS__ID = eINSTANCE.getCheckExists_Id();

    /**
     * The meta object literal for the '<em><b>Varname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECK_EXISTS__VARNAME = eINSTANCE.getCheckExists_Varname();

    /**
     * The meta object literal for the '{@link org.project.browserautomation.bad.impl.ClickOnImpl <em>Click On</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.project.browserautomation.bad.impl.ClickOnImpl
     * @see org.project.browserautomation.bad.impl.BadPackageImpl#getClickOn()
     * @generated
     */
    EClass CLICK_ON = eINSTANCE.getClickOn();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK_ON__TYPE = eINSTANCE.getClickOn_Type();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK_ON__ID = eINSTANCE.getClickOn_Id();

    /**
     * The meta object literal for the '<em><b>Varname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK_ON__VARNAME = eINSTANCE.getClickOn_Varname();

    /**
     * The meta object literal for the '<em><b>Pos index</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK_ON__POS_INDEX = eINSTANCE.getClickOn_Pos_index();

    /**
     * The meta object literal for the '<em><b>Id combo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK_ON__ID_COMBO = eINSTANCE.getClickOn_Id_combo();

    /**
     * The meta object literal for the '<em><b>To select</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK_ON__TO_SELECT = eINSTANCE.getClickOn_To_select();

    /**
     * The meta object literal for the '{@link org.project.browserautomation.bad.impl.CheckboxActionImpl <em>Checkbox Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.project.browserautomation.bad.impl.CheckboxActionImpl
     * @see org.project.browserautomation.bad.impl.BadPackageImpl#getCheckboxAction()
     * @generated
     */
    EClass CHECKBOX_ACTION = eINSTANCE.getCheckboxAction();

    /**
     * The meta object literal for the '<em><b>Bool</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECKBOX_ACTION__BOOL = eINSTANCE.getCheckboxAction_Bool();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECKBOX_ACTION__ACTIONS = eINSTANCE.getCheckboxAction_Actions();

    /**
     * The meta object literal for the '{@link org.project.browserautomation.bad.impl.FillFieldImpl <em>Fill Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.project.browserautomation.bad.impl.FillFieldImpl
     * @see org.project.browserautomation.bad.impl.BadPackageImpl#getFillField()
     * @generated
     */
    EClass FILL_FIELD = eINSTANCE.getFillField();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL_FIELD__ID = eINSTANCE.getFillField_Id();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL_FIELD__VALUE = eINSTANCE.getFillField_Value();

    /**
     * The meta object literal for the '<em><b>Varname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL_FIELD__VARNAME = eINSTANCE.getFillField_Varname();

    /**
     * The meta object literal for the '{@link org.project.browserautomation.bad.impl.StoreElementImpl <em>Store Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.project.browserautomation.bad.impl.StoreElementImpl
     * @see org.project.browserautomation.bad.impl.BadPackageImpl#getStoreElement()
     * @generated
     */
    EClass STORE_ELEMENT = eINSTANCE.getStoreElement();

    /**
     * The meta object literal for the '<em><b>Pos index</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORE_ELEMENT__POS_INDEX = eINSTANCE.getStoreElement_Pos_index();

    /**
     * The meta object literal for the '<em><b>Id from</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORE_ELEMENT__ID_FROM = eINSTANCE.getStoreElement_Id_from();

    /**
     * The meta object literal for the '<em><b>Prop name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORE_ELEMENT__PROP_NAME = eINSTANCE.getStoreElement_Prop_name();

    /**
     * The meta object literal for the '<em><b>Varname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORE_ELEMENT__VARNAME = eINSTANCE.getStoreElement_Varname();

    /**
     * The meta object literal for the '{@link org.project.browserautomation.bad.ClickType <em>Click Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.project.browserautomation.bad.ClickType
     * @see org.project.browserautomation.bad.impl.BadPackageImpl#getClickType()
     * @generated
     */
    EEnum CLICK_TYPE = eINSTANCE.getClickType();

    /**
     * The meta object literal for the '{@link org.project.browserautomation.bad.ElemType <em>Elem Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.project.browserautomation.bad.ElemType
     * @see org.project.browserautomation.bad.impl.BadPackageImpl#getElemType()
     * @generated
     */
    EEnum ELEM_TYPE = eINSTANCE.getElemType();

    /**
     * The meta object literal for the '{@link org.project.browserautomation.bad.BoolString <em>Bool String</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.project.browserautomation.bad.BoolString
     * @see org.project.browserautomation.bad.impl.BadPackageImpl#getBoolString()
     * @generated
     */
    EEnum BOOL_STRING = eINSTANCE.getBoolString();

  }

} //BadPackage
