/**
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation.bad;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Check Exists</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.project.browserautomation.bad.CheckExists#getType <em>Type</em>}</li>
 *   <li>{@link org.project.browserautomation.bad.CheckExists#getId <em>Id</em>}</li>
 *   <li>{@link org.project.browserautomation.bad.CheckExists#getVarname <em>Varname</em>}</li>
 * </ul>
 *
 * @see org.project.browserautomation.bad.BadPackage#getCheckExists()
 * @model
 * @generated
 */
public interface CheckExists extends Instruction
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.project.browserautomation.bad.ElemType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.project.browserautomation.bad.ElemType
   * @see #setType(ElemType)
   * @see org.project.browserautomation.bad.BadPackage#getCheckExists_Type()
   * @model
   * @generated
   */
  ElemType getType();

  /**
   * Sets the value of the '{@link org.project.browserautomation.bad.CheckExists#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.project.browserautomation.bad.ElemType
   * @see #getType()
   * @generated
   */
  void setType(ElemType value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.project.browserautomation.bad.BadPackage#getCheckExists_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.project.browserautomation.bad.CheckExists#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Varname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Varname</em>' attribute.
   * @see #setVarname(String)
   * @see org.project.browserautomation.bad.BadPackage#getCheckExists_Varname()
   * @model
   * @generated
   */
  String getVarname();

  /**
   * Sets the value of the '{@link org.project.browserautomation.bad.CheckExists#getVarname <em>Varname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Varname</em>' attribute.
   * @see #getVarname()
   * @generated
   */
  void setVarname(String value);

} // CheckExists
