/**
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation.bad;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Checkbox Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.project.browserautomation.bad.CheckboxAction#getBool <em>Bool</em>}</li>
 *   <li>{@link org.project.browserautomation.bad.CheckboxAction#getActions <em>Actions</em>}</li>
 * </ul>
 *
 * @see org.project.browserautomation.bad.BadPackage#getCheckboxAction()
 * @model
 * @generated
 */
public interface CheckboxAction extends Instruction
{
  /**
   * Returns the value of the '<em><b>Bool</b></em>' attribute.
   * The literals are from the enumeration {@link org.project.browserautomation.bad.BoolString}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool</em>' attribute.
   * @see org.project.browserautomation.bad.BoolString
   * @see #setBool(BoolString)
   * @see org.project.browserautomation.bad.BadPackage#getCheckboxAction_Bool()
   * @model
   * @generated
   */
  BoolString getBool();

  /**
   * Sets the value of the '{@link org.project.browserautomation.bad.CheckboxAction#getBool <em>Bool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool</em>' attribute.
   * @see org.project.browserautomation.bad.BoolString
   * @see #getBool()
   * @generated
   */
  void setBool(BoolString value);

  /**
   * Returns the value of the '<em><b>Actions</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' attribute list.
   * @see org.project.browserautomation.bad.BadPackage#getCheckboxAction_Actions()
   * @model unique="false"
   * @generated
   */
  EList<String> getActions();

} // CheckboxAction
