/**
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation.bad;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Navigate To Url</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.project.browserautomation.bad.NavigateToUrl#getUrl <em>Url</em>}</li>
 * </ul>
 *
 * @see org.project.browserautomation.bad.BadPackage#getNavigateToUrl()
 * @model
 * @generated
 */
public interface NavigateToUrl extends Instruction
{
  /**
   * Returns the value of the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Url</em>' attribute.
   * @see #setUrl(String)
   * @see org.project.browserautomation.bad.BadPackage#getNavigateToUrl_Url()
   * @model
   * @generated
   */
  String getUrl();

  /**
   * Sets the value of the '{@link org.project.browserautomation.bad.NavigateToUrl#getUrl <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Url</em>' attribute.
   * @see #getUrl()
   * @generated
   */
  void setUrl(String value);

} // NavigateToUrl
