/**
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation.bad;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Store Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.project.browserautomation.bad.StoreElement#getPos_index <em>Pos index</em>}</li>
 *   <li>{@link org.project.browserautomation.bad.StoreElement#getId_from <em>Id from</em>}</li>
 *   <li>{@link org.project.browserautomation.bad.StoreElement#getProp_name <em>Prop name</em>}</li>
 *   <li>{@link org.project.browserautomation.bad.StoreElement#getVarname <em>Varname</em>}</li>
 * </ul>
 *
 * @see org.project.browserautomation.bad.BadPackage#getStoreElement()
 * @model
 * @generated
 */
public interface StoreElement extends Instruction
{
  /**
   * Returns the value of the '<em><b>Pos index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pos index</em>' attribute.
   * @see #setPos_index(int)
   * @see org.project.browserautomation.bad.BadPackage#getStoreElement_Pos_index()
   * @model
   * @generated
   */
  int getPos_index();

  /**
   * Sets the value of the '{@link org.project.browserautomation.bad.StoreElement#getPos_index <em>Pos index</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pos index</em>' attribute.
   * @see #getPos_index()
   * @generated
   */
  void setPos_index(int value);

  /**
   * Returns the value of the '<em><b>Id from</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id from</em>' attribute.
   * @see #setId_from(String)
   * @see org.project.browserautomation.bad.BadPackage#getStoreElement_Id_from()
   * @model
   * @generated
   */
  String getId_from();

  /**
   * Sets the value of the '{@link org.project.browserautomation.bad.StoreElement#getId_from <em>Id from</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id from</em>' attribute.
   * @see #getId_from()
   * @generated
   */
  void setId_from(String value);

  /**
   * Returns the value of the '<em><b>Prop name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prop name</em>' attribute.
   * @see #setProp_name(String)
   * @see org.project.browserautomation.bad.BadPackage#getStoreElement_Prop_name()
   * @model
   * @generated
   */
  String getProp_name();

  /**
   * Sets the value of the '{@link org.project.browserautomation.bad.StoreElement#getProp_name <em>Prop name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prop name</em>' attribute.
   * @see #getProp_name()
   * @generated
   */
  void setProp_name(String value);

  /**
   * Returns the value of the '<em><b>Varname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Varname</em>' attribute.
   * @see #setVarname(String)
   * @see org.project.browserautomation.bad.BadPackage#getStoreElement_Varname()
   * @model
   * @generated
   */
  String getVarname();

  /**
   * Sets the value of the '{@link org.project.browserautomation.bad.StoreElement#getVarname <em>Varname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Varname</em>' attribute.
   * @see #getVarname()
   * @generated
   */
  void setVarname(String value);

} // StoreElement
