/*
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.project.browserautomation.ui.internal.BrowserautomationActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BadExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(BrowserautomationActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		BrowserautomationActivator activator = BrowserautomationActivator.getInstance();
		return activator != null ? activator.getInjector(BrowserautomationActivator.ORG_PROJECT_BROWSERAUTOMATION_BAD) : null;
	}

}
