/*
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBadScopeProvider extends DelegatingScopeProvider {
}
