/**
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation.bad.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.project.browserautomation.bad.BadPackage;
import org.project.browserautomation.bad.StoreElement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Store Element</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.project.browserautomation.bad.impl.StoreElementImpl#getPos_index <em>Pos index</em>}</li>
 *   <li>{@link org.project.browserautomation.bad.impl.StoreElementImpl#getId_from <em>Id from</em>}</li>
 *   <li>{@link org.project.browserautomation.bad.impl.StoreElementImpl#getProp_name <em>Prop name</em>}</li>
 *   <li>{@link org.project.browserautomation.bad.impl.StoreElementImpl#getVarname <em>Varname</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StoreElementImpl extends InstructionImpl implements StoreElement
{
  /**
   * The default value of the '{@link #getPos_index() <em>Pos index</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPos_index()
   * @generated
   * @ordered
   */
  protected static final int POS_INDEX_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPos_index() <em>Pos index</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPos_index()
   * @generated
   * @ordered
   */
  protected int pos_index = POS_INDEX_EDEFAULT;

  /**
   * The default value of the '{@link #getId_from() <em>Id from</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId_from()
   * @generated
   * @ordered
   */
  protected static final String ID_FROM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId_from() <em>Id from</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId_from()
   * @generated
   * @ordered
   */
  protected String id_from = ID_FROM_EDEFAULT;

  /**
   * The default value of the '{@link #getProp_name() <em>Prop name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProp_name()
   * @generated
   * @ordered
   */
  protected static final String PROP_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getProp_name() <em>Prop name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProp_name()
   * @generated
   * @ordered
   */
  protected String prop_name = PROP_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getVarname() <em>Varname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarname()
   * @generated
   * @ordered
   */
  protected static final String VARNAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVarname() <em>Varname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarname()
   * @generated
   * @ordered
   */
  protected String varname = VARNAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StoreElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BadPackage.Literals.STORE_ELEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPos_index()
  {
    return pos_index;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPos_index(int newPos_index)
  {
    int oldPos_index = pos_index;
    pos_index = newPos_index;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BadPackage.STORE_ELEMENT__POS_INDEX, oldPos_index, pos_index));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getId_from()
  {
    return id_from;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setId_from(String newId_from)
  {
    String oldId_from = id_from;
    id_from = newId_from;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BadPackage.STORE_ELEMENT__ID_FROM, oldId_from, id_from));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getProp_name()
  {
    return prop_name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProp_name(String newProp_name)
  {
    String oldProp_name = prop_name;
    prop_name = newProp_name;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BadPackage.STORE_ELEMENT__PROP_NAME, oldProp_name, prop_name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVarname()
  {
    return varname;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVarname(String newVarname)
  {
    String oldVarname = varname;
    varname = newVarname;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BadPackage.STORE_ELEMENT__VARNAME, oldVarname, varname));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BadPackage.STORE_ELEMENT__POS_INDEX:
        return getPos_index();
      case BadPackage.STORE_ELEMENT__ID_FROM:
        return getId_from();
      case BadPackage.STORE_ELEMENT__PROP_NAME:
        return getProp_name();
      case BadPackage.STORE_ELEMENT__VARNAME:
        return getVarname();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BadPackage.STORE_ELEMENT__POS_INDEX:
        setPos_index((Integer)newValue);
        return;
      case BadPackage.STORE_ELEMENT__ID_FROM:
        setId_from((String)newValue);
        return;
      case BadPackage.STORE_ELEMENT__PROP_NAME:
        setProp_name((String)newValue);
        return;
      case BadPackage.STORE_ELEMENT__VARNAME:
        setVarname((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BadPackage.STORE_ELEMENT__POS_INDEX:
        setPos_index(POS_INDEX_EDEFAULT);
        return;
      case BadPackage.STORE_ELEMENT__ID_FROM:
        setId_from(ID_FROM_EDEFAULT);
        return;
      case BadPackage.STORE_ELEMENT__PROP_NAME:
        setProp_name(PROP_NAME_EDEFAULT);
        return;
      case BadPackage.STORE_ELEMENT__VARNAME:
        setVarname(VARNAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BadPackage.STORE_ELEMENT__POS_INDEX:
        return pos_index != POS_INDEX_EDEFAULT;
      case BadPackage.STORE_ELEMENT__ID_FROM:
        return ID_FROM_EDEFAULT == null ? id_from != null : !ID_FROM_EDEFAULT.equals(id_from);
      case BadPackage.STORE_ELEMENT__PROP_NAME:
        return PROP_NAME_EDEFAULT == null ? prop_name != null : !PROP_NAME_EDEFAULT.equals(prop_name);
      case BadPackage.STORE_ELEMENT__VARNAME:
        return VARNAME_EDEFAULT == null ? varname != null : !VARNAME_EDEFAULT.equals(varname);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (pos_index: ");
    result.append(pos_index);
    result.append(", id_from: ");
    result.append(id_from);
    result.append(", prop_name: ");
    result.append(prop_name);
    result.append(", varname: ");
    result.append(varname);
    result.append(')');
    return result.toString();
  }

} //StoreElementImpl
