/*
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.project.browserautomation.ui.internal.BrowserautomationActivator;

public class BadUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BrowserautomationActivator.getInstance().getInjector("org.project.browserautomation.Bad");
	}

}
