/**
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation.bad.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.project.browserautomation.bad.BadPackage;
import org.project.browserautomation.bad.ClickOn;
import org.project.browserautomation.bad.ClickType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Click On</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.project.browserautomation.bad.impl.ClickOnImpl#getType <em>Type</em>}</li>
 *   <li>{@link org.project.browserautomation.bad.impl.ClickOnImpl#getId <em>Id</em>}</li>
 *   <li>{@link org.project.browserautomation.bad.impl.ClickOnImpl#getVarname <em>Varname</em>}</li>
 *   <li>{@link org.project.browserautomation.bad.impl.ClickOnImpl#getPos_index <em>Pos index</em>}</li>
 *   <li>{@link org.project.browserautomation.bad.impl.ClickOnImpl#getId_combo <em>Id combo</em>}</li>
 *   <li>{@link org.project.browserautomation.bad.impl.ClickOnImpl#getTo_select <em>To select</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ClickOnImpl extends InstructionImpl implements ClickOn
{
  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final ClickType TYPE_EDEFAULT = ClickType.BUTTON;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected ClickType type = TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final String ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected String id = ID_EDEFAULT;

  /**
   * The default value of the '{@link #getVarname() <em>Varname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarname()
   * @generated
   * @ordered
   */
  protected static final String VARNAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVarname() <em>Varname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarname()
   * @generated
   * @ordered
   */
  protected String varname = VARNAME_EDEFAULT;

  /**
   * The default value of the '{@link #getPos_index() <em>Pos index</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPos_index()
   * @generated
   * @ordered
   */
  protected static final int POS_INDEX_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPos_index() <em>Pos index</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPos_index()
   * @generated
   * @ordered
   */
  protected int pos_index = POS_INDEX_EDEFAULT;

  /**
   * The default value of the '{@link #getId_combo() <em>Id combo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId_combo()
   * @generated
   * @ordered
   */
  protected static final String ID_COMBO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId_combo() <em>Id combo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId_combo()
   * @generated
   * @ordered
   */
  protected String id_combo = ID_COMBO_EDEFAULT;

  /**
   * The default value of the '{@link #getTo_select() <em>To select</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTo_select()
   * @generated
   * @ordered
   */
  protected static final String TO_SELECT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTo_select() <em>To select</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTo_select()
   * @generated
   * @ordered
   */
  protected String to_select = TO_SELECT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ClickOnImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BadPackage.Literals.CLICK_ON;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ClickType getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(ClickType newType)
  {
    ClickType oldType = type;
    type = newType == null ? TYPE_EDEFAULT : newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BadPackage.CLICK_ON__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setId(String newId)
  {
    String oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BadPackage.CLICK_ON__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVarname()
  {
    return varname;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVarname(String newVarname)
  {
    String oldVarname = varname;
    varname = newVarname;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BadPackage.CLICK_ON__VARNAME, oldVarname, varname));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPos_index()
  {
    return pos_index;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPos_index(int newPos_index)
  {
    int oldPos_index = pos_index;
    pos_index = newPos_index;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BadPackage.CLICK_ON__POS_INDEX, oldPos_index, pos_index));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getId_combo()
  {
    return id_combo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setId_combo(String newId_combo)
  {
    String oldId_combo = id_combo;
    id_combo = newId_combo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BadPackage.CLICK_ON__ID_COMBO, oldId_combo, id_combo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTo_select()
  {
    return to_select;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTo_select(String newTo_select)
  {
    String oldTo_select = to_select;
    to_select = newTo_select;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BadPackage.CLICK_ON__TO_SELECT, oldTo_select, to_select));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BadPackage.CLICK_ON__TYPE:
        return getType();
      case BadPackage.CLICK_ON__ID:
        return getId();
      case BadPackage.CLICK_ON__VARNAME:
        return getVarname();
      case BadPackage.CLICK_ON__POS_INDEX:
        return getPos_index();
      case BadPackage.CLICK_ON__ID_COMBO:
        return getId_combo();
      case BadPackage.CLICK_ON__TO_SELECT:
        return getTo_select();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BadPackage.CLICK_ON__TYPE:
        setType((ClickType)newValue);
        return;
      case BadPackage.CLICK_ON__ID:
        setId((String)newValue);
        return;
      case BadPackage.CLICK_ON__VARNAME:
        setVarname((String)newValue);
        return;
      case BadPackage.CLICK_ON__POS_INDEX:
        setPos_index((Integer)newValue);
        return;
      case BadPackage.CLICK_ON__ID_COMBO:
        setId_combo((String)newValue);
        return;
      case BadPackage.CLICK_ON__TO_SELECT:
        setTo_select((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BadPackage.CLICK_ON__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case BadPackage.CLICK_ON__ID:
        setId(ID_EDEFAULT);
        return;
      case BadPackage.CLICK_ON__VARNAME:
        setVarname(VARNAME_EDEFAULT);
        return;
      case BadPackage.CLICK_ON__POS_INDEX:
        setPos_index(POS_INDEX_EDEFAULT);
        return;
      case BadPackage.CLICK_ON__ID_COMBO:
        setId_combo(ID_COMBO_EDEFAULT);
        return;
      case BadPackage.CLICK_ON__TO_SELECT:
        setTo_select(TO_SELECT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BadPackage.CLICK_ON__TYPE:
        return type != TYPE_EDEFAULT;
      case BadPackage.CLICK_ON__ID:
        return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
      case BadPackage.CLICK_ON__VARNAME:
        return VARNAME_EDEFAULT == null ? varname != null : !VARNAME_EDEFAULT.equals(varname);
      case BadPackage.CLICK_ON__POS_INDEX:
        return pos_index != POS_INDEX_EDEFAULT;
      case BadPackage.CLICK_ON__ID_COMBO:
        return ID_COMBO_EDEFAULT == null ? id_combo != null : !ID_COMBO_EDEFAULT.equals(id_combo);
      case BadPackage.CLICK_ON__TO_SELECT:
        return TO_SELECT_EDEFAULT == null ? to_select != null : !TO_SELECT_EDEFAULT.equals(to_select);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (type: ");
    result.append(type);
    result.append(", id: ");
    result.append(id);
    result.append(", varname: ");
    result.append(varname);
    result.append(", pos_index: ");
    result.append(pos_index);
    result.append(", id_combo: ");
    result.append(id_combo);
    result.append(", to_select: ");
    result.append(to_select);
    result.append(')');
    return result.toString();
  }

} //ClickOnImpl
