/*
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.project.browserautomation.BadRuntimeModule;
import org.project.browserautomation.BadStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BadIdeSetup extends BadStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BadRuntimeModule(), new BadIdeModule()));
	}
	
}
