/*
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BadStandaloneSetup extends BadStandaloneSetupGenerated {

	public static void doSetup() {
		new BadStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
