/*
 * generated by Xtext 2.36.0
 */
package org.project.browserautomation.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BadUiModule extends AbstractBadUiModule {

	public BadUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
